swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /pets/{name}:
    get:
      tags:
        - "pet"
      summary: "Get all the pets and give a name for no reason"
      description: ""
      operationId: "getPets"
      produces:
        - "application/json"
      parameters:
        - name: name
          in: path
          description: The name of your cuddly pet
          required: true
          type: string
      responses:
        200:
          description: "Congratulations! You got pets!"
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
        405:
          description: "Invalid input"
    post:
      tags: 
        - "pet"
      summary: "Get a new pet!"
      description: ""
      operationId: "savePet"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Congratulations! You have a new pet!"
          schema:
            $ref: "#/definitions/Pet"
        405:
          description: "Something is wrong with your pet"
      parameters:
        - name: pet
          in: body
          description: Your new cuddly friend
          required: true
          schema:
            $ref: "#/definitions/Pet"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Pet:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "string"
        example: "91js81jwusau9a82ua8"
      name:
        type: "string"
        example: "Snowball"
      status:
        type: "string"
        description: "pet status in the store"
    xml:
      name: "Pet"
  ApiResponseThingy:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"