version: '3'
services:
  temp:
    image: temp:latest
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    ports:
    - 8080:8080
  temp-mongodb:
    image: mongo:3.6.3
    volumes:
    - mongo-temp:/data/db
volumes:
  mongo-temp:
